questions =  [
    {"id": 0, "question": "if we give jay admin then bleedcord will collapse", "effects": {"auth": -1}},
    {"id": 1, "question": "fatman ahh blud.wav has caused detrimental issues to bleedcord", "effects": {"auth": 1}},
    {"id": 2, "question": "it is favorable to rename the collective to troupe, for bleed is just too outdated", "effects": {"right": 1}},
    {"id": 3, "question": "leather jackets are fashionable", "effects": {"auth": -1}},
    {"id": 4, "question": "any food that is manmade must to be banned", "effects": {"auth": -1}},
    {"id": 5, "question": "13 body count is acceptable", "effects": {"prog": -1}},
    {"id": 6, "question": "melt-maxxing is extremely triggering to me", "effects": {"prog": -1}},
    {"id": 7, "question": "pol pot did nothing wrong he js didnt like ppl who wore glasses", "effects": {"right": 1}},
    {"id": 8, "question": "leather jackets are fashionable", "effects": {"auth": -1}},
    {"id": 9, "question": "at first at first is overall better than the brave little abacus", "effects": {"auth": 1}},
    {"id": 10, "question": "ccryden was a generally better bleood clone than jay", "effects": {"auth": -1}},
    {"id": 11, "question": "dars sweats are fire", "effects": {"auth": -1}},
    {"id": 12, "question": "we need to gathering the funds in order to provide for ourselves", "effects": {"right": 1}},
    {"id": 13, "question": "mormons are retarded", "effects": {"prog": 1}},
    {"id": 14, "question": "brns is retarded", "effects": {"prog": 1}},
    {"id": 15, "question": "sleep can directly combat stomach issues", "effects": {"prog": 1}},
    {"id": 16, "question": "life in bleedcord was much better before jay joined", "effects": {"auth": -2}},
    {"id": 17, "question": "me n my kup stems would basically change the world and bring world peace", "effects": {"right": 1}},
    {"id": 18, "question": "the yo was better when the world was free", "effects": {"right": 1}},
    {"id": 19, "question": "xzuji is a fucking bitch and a geek and a threat to humanity jesus christ i hate him", "effects": {"right": 2}},
    {"id": 20, "question": "the yo was better when the world was free", "effects": {"right": 1}},
    {"id": 21, "question": "spireism is idealy flawed because the monopolies of brnsism dont exist today", "effects": {"right": 1}},
    {"id": 22, "question": "we must tax the admin", "effects": {"right": -1}},
    {"id": 23, "question": "welfare and care should be given to those with no admin", "effects": {"right": -1}},
    {"id": 24, "question": "we must tax the admin", "effects": {"right": -1}},
    {"id": 25, "question": "alikards fever must be cured effected immedietly or else his doctors suck", "effects": {"[prog": -1}},
    {"id": 26, "question": "molt and dar are the anti christ and they must be executed", "effects": {"[auth": -1}},
    {"id": 27, "question": "due to alikards longer experience in life, we should followhis footsteps; he clearly knows what he is doing", "effects": {"[prog": -1}},
    {"id": 28, "question": "the hellp is the greatest band of all time", "effects": {"[auth": -2}},
    {"id": 29, "question": "the less you weigh the better you feel about yourself", "effects": {"[auth": -1}},
    {"id": 30, "question": "dar is just a skinny worthless geek who sits at his pc all day", "effects": {"[auth": -2}},
    {"id": 31, "question": "the hellp is the greatest band of all time", "effects": {"[auth": -1}},
    {"id": 32, "question": "deleting frags old server was a good thing, because bleed2026 would have never been formed", "effects": {"[prog": 1}},
    {"id": 33, "question": "radical jayism is a more achievable and overall a better ideology than moderate jaysim", "effects": {"[auth": 2}},
    {"id": 34, "question": "ragebaiting frag is funny", "effects": {"[auth": 1}},
    {"id": 35, "question": "right-brnism is a realistic adn achievable ideology", "effects": {"[right": 3}},
    {"id": 36, "question": "multiple admins will lead to a safer bleedcord because nobody is able to ban anybody", "effects": {"[auth": -2}},
    {"id": 37, "question": "nothing happened in tianamenn square 1989 praise mao", "effects": {"[right": -3}},
    {"id": 38, "question": "molt is hitler", "effects": {"[auth": -1}},
    {"id": 39, "question": "dar is hitler", "effects": {"[auth": -1}},
    {"id": 40, "question": "brns is pol pot", "effects": {"[right": 1}},
    {"id": 41, "question": "brns is running out of questions and getting lazier", "effects": {"[right": -1}},
    {"id": 42, "question": "yeah... both sides are bad actually...", "effects": {"[prog": -1}},
    {"id": 43, "question": "artifical intelligience must be abolished in order to maintain seperation of tennis and bird", "effects": {"[auth": 1}},
    {"id": 44, "question": "bleedcord could unfortnutately take off", "effects": {"[auth": 1}},
    {"id": 45, "question": "brns' nicheness could annailate the world", "effects": {"[right": 1}},
    {"id": 45, "question": "holy shit dude im running out of questions", "effects": {"[auth": -1}},
    {"id": 45, "question": "left or right", "effects": {"[auth": -1}},
    {"id": 45, "question": "@everyone goodnight", "effects": {"[right": 2}},
    
        
];
